# -*- coding: utf-8 -*-
"""app_Curitiba3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RHilDFRG0aBo1u3e3REBEeuJF5pSpGjH
"""

import streamlit as st
from streamlit_folium import folium_static
import folium

PAGE_CONFIG = {"page_title":"Aplicação de Mapas","page_icon":":smiley:","layout":"centered"}
st.set_page_config(**PAGE_CONFIG)

def main():
	st.title("Mapa de Curitiba para rotas turísticas")
	st.subheader("Baseado num caderno do Colab")
	menu = ["Home","Mapa"]
	choice = st.sidebar.selectbox('Menu',menu)
	if choice == 'Home':
		st.subheader("Página Inicial")
	elif choice == 'Mapa':
		st.subheader("Visualizar Mapa")
		with st.echo():
			m = folium.Map (location = [-25.5,-49.3], zoom_start =  9)
      folium.Marker([-25.384618,-49.276169], popup="Ópera de Arame", icon=folium.Icon(color='green', icon='star')).add_to(m)
			folium_static(m)
	else:
		st.subheader("")
if __name__ == '__main__':
	main()