# -*- coding: utf-8 -*-
"""APP_PARIS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7gruMGE6PPV2x_tssL477QGKhojQ_E3
"""

import streamlit as st
from streamlit_folium import folium_static
import folium

PAGE_CONFIG = {"page_title":"Aplicação de Mapas","page_icon":":smiley:","layout":"centered"}
st.set_page_config(**PAGE_CONFIG)

def main():
	st.title("Mapa de Paris")
	st.subheader("Baseado num caderno do Colab")
	menu = ["Home","Paris"]
	choice = st.sidebar.selectbox('Menu',menu)
	if choice == 'Home':
		st.subheader("Página Inicial 1")
	elif choice == 'Mapa':
		st.subheader("Visualizar Mapa")
		with st.echo():
			m = folium.Map (location = [48.864716, 2.349014], zoom_start =  9)
			folium_static(m)
	else:
		st.subheader("")
if __name__ == '__main__':
	main()